language: python
python:
  - "2.7"
  - "3.5"
cache:
  apt: true
  directories:
    - $HOME/.cache/pip
addons:
  apt:
    packages:
      - jq
      - libatlas3gf-base
      - libatlas-dev
      - liblapack-dev
before_install:
  - pip install -U pip setuptools wheel
install:
  - pip install .
  - pip install xgboost
  - python -m nltk.downloader stopwords
script:
  - ./benchmark/job_eval.sh
#  - for script in ./benchmark/*.sh; do $script; done
